### PR TITLE
change default shortcuts to reduce conflicts with other software

### PR DESCRIPTION
**Pull request by timbertson**
Over time, other software has muscled in on shellshape shortcuts and taken them for their own use.

This fixes the worst offenders. There are still a couple of gnome shortcuts which conflict with shellshape, but those keybindings are critical to the shellshape layout (e.g super+h, super+l) or too convenient to give up (e.g. super+space), so I'm not going to change them.

I'd like to do just one change, if possible. Does anyone have additional shortcuts they want to see changed, or problems / better alternatives to these changes?

 - super+m -> super+x (minimize) - _conflict with gnome-shell "show message tray"_
 - super+shift+m -> super+shift+x (unminimize) - _consistency with above_
 - super+p -> super+; (tile) - _conflict with hardcoded keybinding in gnome-settings-daemon_
 - super+d -> super+v (vertical layout) - _conflict with traditional "show desktop" (still in use on Ubuntu I believe)_

### CODE REVIEW

**Comment by Landkeks** [comment]
> super+p -> super+;

That one is would be inconvenient on non-US keyboard layouts.

**Comment by gfxmonk** [comment]
@Landkeks thanks, good point. It's looking rather crowded, got any good ideas for alternatives? I'd like to keep it in the right-hand side of the keyboard if possible.

**Comment by Landkeks** [comment]
@gfxmonk Do you have a list of the current default shortcuts? You seem to have changed a few shortcuts recently and I'm not using the latest version.

**Comment by gfxmonk** [comment]
@Landkeks the modified gschema file (https://github.com/gfxmonk/shellshape/blob/change_default_shortcuts/schemas/org.gnome.shell.extensions.net.gfxmonk.shellshape.keybindings.gschema.xml) is the canonical list - I've got an update to the shellshape html page as well, but haven't published that yet. `mod4` == `windows key`

**Comment by Landkeks** [comment]
@gfxmonk What about mod4+shift+y, since it's the opposite of mod4+y?

(BTW: None of the shortcuts seems to work on 3.16 right now.)

**Comment by gfxmonk** [comment]
I'm not a big fan of that, since tiling is probably more common that
untiling, so I'd like to keep the shortcut simple (i.e. no Shift). I'm now
leaning towards super+t. It's less ergonomic (harder to reach, at least for
me) but it makes a lot of sense for "tile", and it's also conveniently next
to "y".

**Pull request closed without merging**
